name: Build 

on: [push, pull_request]

env:
  CIBW_BUILD: cp37-* cp38-* cp39-*
  CIBW_SKIP: cp310-*
  CIBW_ARCHS_WINDOWS: "AMD64"
  CIBW_ARCHS_MACOS: "x86_64"
  CIBW_ARCHS_LINUX: "x86_64"
  CIBW_BEFORE_BUILD_WINDOWS: python .github/workflows/prepare.py

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, windows-2019]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install dependencies for macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install fftw

      - name: Install dependencies
        run: python -m pip install wxpython numpy vtk h5py pillow requests

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.1.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl